[build-system]
requires = ["hatchling<=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "awesom"
version = "2.0.0"
description = "Site-of-metabolism prediction with aleatoric and epistemic uncertainty quantification."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT License"}
authors = [
  {name = "Roxane Jacob", email = "roxane.axel.jacob@univie.ac.at"},
]

dependencies = [
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "numpy>=1.26.4,<2",
    "optuna>=4.1.0",
    "pandas>=1.5.2,<2.2.0",
    "rdkit==2023.3.3",
    "scikit-learn>=1.6.1",
    "tensorboard>=2.18.0",
    "torch>=2.5.1",
    "torchmetrics>=1.0.3",
    "torch-geometric>=2.6.1",
    "PyYAML>=6.0",
    "tqdm>=4.64.0",
]

[dependency-groups]
build = ["build"]
ci = [
    "pytest>=8.4.1",
    "ruff>=0.15.16",
    "ty>=0.0.46",
]
cli = [
    "typer>=0.16.0",
]
nerdd = [
    "nerdd-link>=0.5.15",
    "nerdd-module>=0.3.52",
]
dev = [
    { include-group = "build" },
    { include-group = "ci" },
    { include-group = "cli" },
    { include-group = "nerdd" },
]

[project.scripts]
awesom = "awesom._cli:app"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[[tool.ty.overrides]]
include = ["**"]
[tool.ty.overrides.analysis]
replace-imports-with-any = ["rdkit.**"]
